import type { Request, Response, NextFunction } from "express";
import reportService from "./report.service.js";
import sendResponse from "../../utils/sendResponse.js";
import { convertToCSV, convertToExcel } from "../../utils/exporter.js";
import type z from "zod";
import type reportSchema from "./report.schema.js";

type GetSalesAnalyticsRequest = Request<
  unknown,
  unknown,
  unknown,
  z.infer<typeof reportSchema.getSalesAnalyticsSchema>["query"]
>;
type GetSalesAuditTrailRequest = Request<
  unknown,
  unknown,
  unknown,
  z.infer<typeof reportSchema.getSalesAuditTrailSchema>["query"]
>;
type GetInventoryExpiryRequest = Request<
  unknown,
  unknown,
  unknown,
  z.infer<typeof reportSchema.getInventoryExpirySchema>["query"]
>;

const reportController = {
  getSalesAnalytics: async (req: GetSalesAnalyticsRequest, res: Response, next: NextFunction) => {
    try {
      const result = await reportService.getSalesAnalytics({ query: req.query });
      sendResponse(res, 200, "Sales analytics fetched successfully", result);
    } catch (error) {
      next(error);
    }
  },

  getSalesAuditTrail: async (req: GetSalesAuditTrailRequest, res: Response, next: NextFunction) => {
    try {
      const result = await reportService.getSalesAuditTrail({ query: req.query });
      
      if (req.query.format === "csv") {
        const csvString = convertToCSV(result.data!);
        res.setHeader("Content-Type", "text/csv");
        res.setHeader("Content-Disposition", 'attachment; filename="sales_audit_trail.csv"');
        res.status(200).send(csvString);
        return;
      } else if (req.query.format === "excel") {
        const excelBuffer = await convertToExcel(result.data!);
        res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
        res.setHeader("Content-Disposition", 'attachment; filename="sales_audit_trail.xlsx"');
        res.status(200).send(excelBuffer);
        return;
      } else if (req.query.format === "pdf") {
        // Return JSON with a note that frontend can render it, or we can add library later
        sendResponse(res, 200, `Reporting format ${req.query.format} should be generated by frontend or install backend libraries. Returning JSON`, result.data, result.meta ?? undefined);
        return;
      }

      sendResponse(res, 200, "Sales audit trail fetched successfully", result.data, result.meta ?? undefined);
    } catch (error) {
      next(error);
    }
  },

  getInventoryExpiry: async (req: GetInventoryExpiryRequest, res: Response, next: NextFunction) => {
    try {
      const result = await reportService.getInventoryExpiry({ query: req.query });

      if (req.query.format === "csv") {
        const csvString = convertToCSV(result.data!);
        res.setHeader("Content-Type", "text/csv");
        res.setHeader("Content-Disposition", 'attachment; filename="inventory_expiry_alert.csv"');
        res.status(200).send(csvString);
        return;
      } else if (req.query.format === "excel") {
        const excelBuffer = await convertToExcel(result.data!);
        res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
        res.setHeader("Content-Disposition", 'attachment; filename="inventory_expiry_alert.xlsx"');
        res.status(200).send(excelBuffer);
        return;
      } else if (req.query.format === "pdf") {
        sendResponse(res, 200, `Reporting format ${req.query.format} should be generated by frontend or install backend libraries. Returning JSON`, result.data, result.meta ?? undefined);
        return;
      }

      sendResponse(res, 200, "Inventory expiry alert fetched successfully", result.data, result.meta ?? undefined);
    } catch (error) {
      next(error);
    }
  },
};

export default reportController;
